version: '3'
services:
  ws:
    build:
      context: ../..
      dockerfile: docker/imgzip2pdf-cli/Dockerfile
    image: imgzip2pdf-cli
    user: 1000:1000
    volumes:
      - .:/workspace
    working_dir: /workspace
