version: '3'
services:
  ws:
    build:
      context: .
      dockerfile: Dockerfile
    image: imgzip2pdf-dev
    user: 1000:1000
    volumes:
      - ${HOME}/.m2:/home/me/.m2
      - ../..:/imgzip2pdf
    working_dir: /imgzip2pdf
